---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: apache-demo
    component: httpd
spec:
  type: NodePort
  ports:
  - port: ${HTTPD_PORT}
    protocol: TCP
    targetPort: 443
  selector:
    app: apache-demo
    component: httpd
