---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: httpd
  labels:
    app: apache-demo
    component: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-demo
      component: httpd
  template:
    metadata:
      name: httpd-pod
      labels:
        app: apache-demo
        component: httpd
    spec:
      containers:
      - image: spinor72/httpd:${HTTPD_VERSION}
        name: httpd
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
